/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useMemo, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
  I: "viseme_I",
  O: "viseme_O",
  U: "viseme_U",
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene, animations: modelAnimations } = useGLTF(
    "/models/64f1a714fe61576b46f27ca2.glb",
    undefined,
    (error) => {
      console.warn("Error loading main model:", error);
    }
  );

  const { message, onMessagePlayed, currentAudio, currentAnalyser } = useChat();

  const [lipsync, setLipsync] = useState();

  useEffect(() => {
    console.log(message);
    if (!message) {
      setAnimation("Idle");
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);
  }, [message]);

  const { animations } = useGLTF("/models/animations.glb", undefined, (error) => {
    console.warn("Error loading animations:", error);
  });

  // Check if required data is loaded
  const isModelLoaded = nodes && materials && scene;
  const areAnimationsLoaded = animations && animations.length > 0;

  // Filter out animations that reference missing bones
  const filteredAnimations = useMemo(() => {
    if (!areAnimationsLoaded || !scene) return [];
    
    // Get all bone names from the current scene
    const boneNames = new Set();
    scene.traverse((child) => {
      if (child.isBone) {
        boneNames.add(child.name);
      }
    });
    
    // Filter animations to only include those with tracks for existing bones
    return animations.map(animation => {
      const validTracks = animation.tracks.filter(track => {
        // Extract bone name from track path (e.g., "HeadTop_End_end.position" -> "HeadTop_End_end")
        const boneName = track.name.split('.')[0];
        return boneNames.has(boneName);
      });
      
      return {
        ...animation,
        tracks: validTracks
      };
    }).filter(animation => animation.tracks.length > 0); // Only include animations with valid tracks
  }, [animations, scene, areAnimationsLoaded]);

  const group = useRef();
  const { actions, mixer } = useAnimations(isModelLoaded && areAnimationsLoaded ? filteredAnimations : [], group);
  const [animation, setAnimation] = useState("");

  useEffect(() => {
    if (!isModelLoaded || !areAnimationsLoaded || filteredAnimations.length === 0) {
      setAnimation("");
      return;
    }
    
    const newAnimation = filteredAnimations.find((a) => a.name === "Idle") 
      ? "Idle" 
      : filteredAnimations[0]?.name || "";
      
    setAnimation(newAnimation);
  }, [filteredAnimations, isModelLoaded, areAnimationsLoaded]);

  useEffect(() => {
    if (!animation || !actions[animation]) return;
    
    try {
      actions[animation]
        .reset()
        .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
        .play();
      return () => {
        if (actions[animation]) {
          actions[animation].fadeOut(0.5);
        }
      };
    } catch (error) {
      console.warn("Error playing animation:", error);
    }
  }, [animation, actions, mixer.stats.actions.inUse]);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    if (!isModelLoaded) return;
    
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        // Removed Leva control updates to prevent errors
        // Leva controls should not be updated individually like this
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const audioEnergyRef = useRef(0);
  
  useFrame(() => {
    // Only run animation logic if model is loaded
    if (!isModelLoaded || !areAnimationsLoaded) return;
    
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // PROFESSIONAL LIP-SYNC WITH COARTICULATION
    if (setupMode || !message || !lipsync || !currentAudio) {
      // Reset all morph targets when not in use
      Object.values(corresponding).forEach((value) => {
        lerpMorphTarget(value, 0, 0.15);
      });
      return;
    }

    // Update real-time audio amplitude from Web Audio analyser
    if (currentAnalyser?.analyser && currentAnalyser?.dataArray) {
      try {
        currentAnalyser.analyser.getByteTimeDomainData(currentAnalyser.dataArray);
        let sumSquares = 0;
        for (let i = 0; i < currentAnalyser.dataArray.length; i++) {
          const value = (currentAnalyser.dataArray[i] - 128) / 128;
          sumSquares += value * value;
        }
        const rms = Math.sqrt(sumSquares / currentAnalyser.dataArray.length);
        const normalized = Math.min(rms * 3, 1); // Boost energy slightly
        audioEnergyRef.current = audioEnergyRef.current * 0.7 + normalized * 0.3;
      } catch (error) {
        if (process.env.NODE_ENV === 'development') {
          console.warn('Audio analyser processing error:', error);
        }
      }
    } else {
      audioEnergyRef.current *= 0.92;
    }

    const audioEnergy = audioEnergyRef.current;

    const currentAudioTime = currentAudio.currentTime;
    const audioDuration = currentAudio.duration || 1;
    const lastCueEnd = lipsync?.duration && lipsync.duration > 0
      ? lipsync.duration
      : (lipsync.mouthCues?.length ? lipsync.mouthCues[lipsync.mouthCues.length - 1].end || 0 : 0);
    const durationScale = lastCueEnd > 0 ? audioDuration / lastCueEnd : 1;
    
    // Track applied morph targets for smooth transitions
    const appliedMorphTargets = new Set();
    
    // Process mouth cues with coarticulation and anticipatory timing
    if (lipsync.mouthCues && lipsync.mouthCues.length > 0) {
      for (let i = 0; i < lipsync.mouthCues.length; i++) {
        const mouthCue = lipsync.mouthCues[i];
        const cueStart = (mouthCue.start ?? 0) * durationScale;
        const cueEnd = (mouthCue.end ?? 0) * durationScale;
        const effectiveStart = Math.max(cueStart, 0);
        const effectiveEnd = Math.max(cueEnd, effectiveStart + 0.01);

        // Check if we're in the right time window (with anticipation)
        if (currentAudioTime >= effectiveStart && currentAudioTime <= effectiveEnd) {
          const viseme = corresponding[mouthCue.value];
          if (viseme) {
            // Calculate precise interpolation factor within the cue
            const progress = (currentAudioTime - effectiveStart) / (effectiveEnd - effectiveStart);
            
            // Apply easing function for natural acceleration/deceleration
            const easedProgress = 0.5 - 0.5 * Math.cos(progress * Math.PI);
            
            // Base intensity with natural variation
            const baseIntensity = 0.7 + 0.3 * Math.sin(progress * Math.PI);
            
            // Apply coarticulation effects based on adjacent phonemes
            let intensity = baseIntensity;
            let transitionSpeed = 0.25;
            
            // Adjust for specific viseme types
            switch (mouthCue.value) {
              case 'A': // Open vowels
                intensity = baseIntensity * 1.0;
                transitionSpeed = 0.2;
                break;
              case 'E': // Mid vowels
                intensity = baseIntensity * 0.85;
                transitionSpeed = 0.25;
                break;
              case 'I': // High front vowels
                intensity = baseIntensity * 0.7;
                transitionSpeed = 0.3;
                break;
              case 'O': // Rounded vowels
                intensity = baseIntensity * 0.9;
                transitionSpeed = 0.22;
                break;
              case 'U': // High back vowels
                intensity = baseIntensity * 0.8;
                transitionSpeed = 0.28;
                break;
              case 'B': // Bilabials
                intensity = baseIntensity * 0.95;
                transitionSpeed = 0.15; // Faster for plosives
                break;
              case 'F': // Labiodentals
                intensity = baseIntensity * 0.85;
                transitionSpeed = 0.2;
                break;
              case 'H': // Inter/Aveolars
                intensity = baseIntensity * 0.75;
                transitionSpeed = 0.25;
                break;
              case 'X': // Rest/Silence
                intensity = baseIntensity * 0.3;
                transitionSpeed = 0.3;
                break;
            }
            
            // Apply real-time audio energy boost
            const amplitudeBoost = 0.55 + audioEnergy * 0.9;
            intensity = Math.min(intensity * amplitudeBoost, 1.0);

            // Apply primary viseme
            appliedMorphTargets.add(viseme);
            lerpMorphTarget(viseme, intensity, transitionSpeed);
            
            // Apply coarticulation secondary morph targets
            const coarticulationTargets = getCoarticulationTargets(mouthCue);
            Object.entries(coarticulationTargets).forEach(([target, targetIntensity]) => {
              appliedMorphTargets.add(target);
              lerpMorphTarget(target, intensity * targetIntensity, transitionSpeed * 0.8);
            });
            
            // Add subtle jaw movement for vowel sounds
            if (['A', 'E', 'O', 'U'].includes(mouthCue.value)) {
              lerpMorphTarget('jawOpen', intensity * 0.6, transitionSpeed);
            }
            
            // Add cheek involvement for extreme expressions
            if (intensity > 0.8) {
              lerpMorphTarget('cheekSquintLeft', intensity * 0.3, transitionSpeed);
              lerpMorphTarget('cheekSquintRight', intensity * 0.3, transitionSpeed);
            }
          }
          break;
        }
        
        // Handle transitions between cues
        if (i < lipsync.mouthCues.length - 1) {
          const nextCue = lipsync.mouthCues[i + 1];
          const currentEnd = (mouthCue.end ?? 0) * durationScale;
          const nextStart = (nextCue.start ?? 0) * durationScale;
          if (currentAudioTime > currentEnd && currentAudioTime < nextStart) {
            // In transition period - blend between cues
            const transitionProgress = (currentAudioTime - currentEnd) / Math.max(nextStart - currentEnd, 0.01);
            
            const currentViseme = corresponding[mouthCue.value];
            const nextViseme = corresponding[nextCue.value];
            
            if (currentViseme && nextViseme) {
              // Smooth transition between visemes
              appliedMorphTargets.add(currentViseme);
              appliedMorphTargets.add(nextViseme);
              
              lerpMorphTarget(currentViseme, 1 - transitionProgress, 0.15);
              lerpMorphTarget(nextViseme, transitionProgress, 0.15);
              
              // Blend coarticulation effects during transition
              const currentCoartTargets = getCoarticulationTargets(mouthCue);
              const nextCoartTargets = getCoarticulationTargets(nextCue);
              
              // Apply blended coarticulation
              const allTargets = new Set([
                ...Object.keys(currentCoartTargets),
                ...Object.keys(nextCoartTargets)
              ]);
              
              allTargets.forEach(target => {
                const currentIntensity = currentCoartTargets[target] || 0;
                const nextIntensity = nextCoartTargets[target] || 0;
                const blendedIntensity = currentIntensity * (1 - transitionProgress) + nextIntensity * transitionProgress;
                
                appliedMorphTargets.add(target);
                lerpMorphTarget(target, blendedIntensity, 0.15);
              });
            }
          }
        }
      }
    }

    // Natural mouth movement during speech (micro-expressions)
    if (currentAudioTime < audioDuration) {
      const microMovementIntensity = Math.max(audioEnergy * 0.65, 0.08 + 0.04 * Math.sin(currentAudioTime * 15));
      lerpMorphTarget('jawOpen', microMovementIntensity * 0.9, 0.18);
      lerpMorphTarget('viseme_PP', microMovementIntensity * 0.7, 0.15);
      if (microMovementIntensity > 0.4) {
        lerpMorphTarget('cheekSquintLeft', microMovementIntensity * 0.25, 0.2);
        lerpMorphTarget('cheekSquintRight', microMovementIntensity * 0.25, 0.2);
      }
    }

    // If analyser energy is high but no viseme active (e.g., heuristic miss), open jaw slightly
    if (appliedMorphTargets.size === 0 && audioEnergy > 0.15) {
      const fallbackIntensity = Math.min(audioEnergy * 0.85, 0.9);
      lerpMorphTarget('jawOpen', fallbackIntensity, 0.2);
      lerpMorphTarget('viseme_PP', fallbackIntensity * 0.65, 0.2);
    }

    // Fade out unused morph targets smoothly
    Object.values(corresponding).forEach((value) => {
      if (!appliedMorphTargets.has(value)) {
        lerpMorphTarget(value, 0, 0.15);
      }
    });
  });

// Helper function to calculate coarticulation targets
const getCoarticulationTargets = (mouthCue) => {
  const targets = {};
  
  // Base coarticulation based on viseme type
  switch (mouthCue.value) {
    case 'A': // AA - Wide open jaw
      targets['viseme_AA'] = 0.8;
      targets['viseme_PP'] = 0.4;
      targets['jawOpen'] = 0.6;
      break;
    case 'E': // EH - Slightly open
      targets['viseme_O'] = 0.6;
      targets['viseme_FF'] = 0.4;
      break;
    case 'I': // IH - Tight
      targets['viseme_I'] = 0.7;
      targets['viseme_kk'] = 0.5;
      break;
    case 'O': // OH - Rounded
      targets['viseme_O'] = 0.9;
      targets['viseme_PP'] = 0.6;
      break;
    case 'U': // UH - Tight rounded
      targets['viseme_U'] = 0.8;
      targets['viseme_kk'] = 0.4;
      break;
    case 'B': // PP - Closed lips
      targets['viseme_PP'] = 1.0;
      targets['viseme_kk'] = 0.3;
      break;
    case 'F': // FF - Upper teeth on lower lip
      targets['viseme_FF'] = 0.9;
      targets['viseme_TH'] = 0.6;
      break;
    case 'H': // TH - Tongue between teeth
      targets['viseme_TH'] = 0.8;
      targets['viseme_FF'] = 0.5;
      break;
    case 'G': // KK - Back of tongue raised
      targets['viseme_kk'] = 0.7;
      targets['viseme_TH'] = 0.4;
      break;
  }
  
  // Influence from previous phoneme
  if (mouthCue.prevPhoneme) {
    // Carryover effects from previous sound
    switch (mouthCue.prevPhoneme) {
      case 'b':
      case 'p':
      case 'm':
        targets['viseme_PP'] = (targets['viseme_PP'] || 0) + 0.2;
        break;
      case 'f':
      case 'v':
        targets['viseme_FF'] = (targets['viseme_FF'] || 0) + 0.2;
        break;
    }
  }
  
  // Influence from next phoneme (anticipatory coarticulation)
  if (mouthCue.nextPhoneme) {
    // Prepare for upcoming sound
    switch (mouthCue.nextPhoneme) {
      case 'b':
      case 'p':
      case 'm':
        targets['viseme_PP'] = (targets['viseme_PP'] || 0) + 0.15;
        break;
      case 'f':
      case 'v':
        targets['viseme_FF'] = (targets['viseme_FF'] || 0) + 0.15;
        break;
    }
  }
  
  return targets;
};

  useControls("FacialExpressions", {
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: filteredAnimations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      if (!isModelLoaded) return;
      
      try {
        const emotionValues = {};
        Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
          if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
            return; // eyes wink/blink are handled separately
          }
          try {
            const index = nodes.EyeLeft.morphTargetDictionary[key];
            if (index !== undefined) {
              const value = nodes.EyeLeft.morphTargetInfluences[index];
              if (value !== undefined && value > 0.01) {
                emotionValues[key] = value;
              }
            }
          } catch (e) {
            // Skip invalid morph targets
            if (process.env.NODE_ENV === 'development') {
              console.warn(`Error reading morph target ${key}:`, e);
            }
          }
        });
        console.log(JSON.stringify(emotionValues, null, 2));
      } catch (e) {
        console.warn('Error logging morph target values:', e);
      }
    }),
  });

  const [, set] = useControls("MorphTarget", () => {
    // Return an empty object to avoid Leva errors
    // The morph target controls were causing too many issues with dynamic updates
    return {};
  });

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <>
      {isModelLoaded ? (
        <group {...props} dispose={null} ref={group}>
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            skeleton={nodes.Wolf3D_Body.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            skeleton={nodes.Wolf3D_Hair.skeleton}
          />
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
        </group>
      ) : (
        <group {...props} ref={group}>
          {/* Loading placeholder or fallback */}
          <mesh>
            <boxGeometry args={[1, 1, 1]} />
            <meshStandardMaterial color="gray" wireframe />
          </mesh>
        </group>
      )}
    </>
  );
}

useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/animations.glb");