/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useMemo, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene, animations: modelAnimations } = useGLTF(
    "/models/64f1a714fe61576b46f27ca2.glb",
    undefined,
    (error) => {
      console.warn("Error loading main model:", error);
    }
  );

  const { message, onMessagePlayed, currentAudio } = useChat();

  const [lipsync, setLipsync] = useState();

  useEffect(() => {
    console.log(message);
    if (!message) {
      setAnimation("Idle");
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);
  }, [message]);

  const { animations } = useGLTF("/models/animations.glb", undefined, (error) => {
    console.warn("Error loading animations:", error);
  });

  // Check if required data is loaded
  const isModelLoaded = nodes && materials && scene;
  const areAnimationsLoaded = animations && animations.length > 0;

  // Filter out animations that reference missing bones
  const filteredAnimations = useMemo(() => {
    if (!areAnimationsLoaded || !scene) return [];
    
    // Get all bone names from the current scene
    const boneNames = new Set();
    scene.traverse((child) => {
      if (child.isBone) {
        boneNames.add(child.name);
      }
    });
    
    // Filter animations to only include those with tracks for existing bones
    return animations.map(animation => {
      const validTracks = animation.tracks.filter(track => {
        // Extract bone name from track path (e.g., "HeadTop_End_end.position" -> "HeadTop_End_end")
        const boneName = track.name.split('.')[0];
        return boneNames.has(boneName);
      });
      
      return {
        ...animation,
        tracks: validTracks
      };
    }).filter(animation => animation.tracks.length > 0); // Only include animations with valid tracks
  }, [animations, scene, areAnimationsLoaded]);

  const group = useRef();
  const { actions, mixer } = useAnimations(isModelLoaded && areAnimationsLoaded ? filteredAnimations : [], group);
  const [animation, setAnimation] = useState("");

  useEffect(() => {
    if (!isModelLoaded || !areAnimationsLoaded || filteredAnimations.length === 0) {
      setAnimation("");
      return;
    }
    
    const newAnimation = filteredAnimations.find((a) => a.name === "Idle") 
      ? "Idle" 
      : filteredAnimations[0]?.name || "";
      
    setAnimation(newAnimation);
  }, [filteredAnimations, isModelLoaded, areAnimationsLoaded]);

  useEffect(() => {
    if (!animation || !actions[animation]) return;
    
    try {
      actions[animation]
        .reset()
        .fadeIn(mixer.stats.actions.inUse === 0 ? 0 : 0.5)
        .play();
      return () => {
        if (actions[animation]) {
          actions[animation].fadeOut(0.5);
        }
      };
    } catch (error) {
      console.warn("Error playing animation:", error);
    }
  }, [animation, actions, mixer.stats.actions.inUse]);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    if (!isModelLoaded) return;
    
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        // Removed Leva control updates to prevent errors
        // Leva controls should not be updated individually like this
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  
  useFrame(() => {
    // Only run animation logic if model is loaded
    if (!isModelLoaded || !areAnimationsLoaded) return;
    
    !setupMode &&
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // ENHANCED LIPSYNC - Maximum mouth activity during voice playback
    if (setupMode || !message || !lipsync || !currentAudio) {
      return;
    }

    const currentAudioTime = currentAudio.currentTime;
    const audioDuration = currentAudio.duration || 1;
    const appliedMorphTargets = [];
    
    // Calculate total lipsync duration and scale to match audio
    const totalLipsyncDuration = lipsync.mouthCues.length > 0 
      ? lipsync.mouthCues[lipsync.mouthCues.length - 1].end 
      : 1;
    
    const timeScale = audioDuration / totalLipsyncDuration;
    
    // Check current and next mouth cues for maximum activity
    for (let i = 0; i < lipsync.mouthCues.length; i++) {
      const mouthCue = lipsync.mouthCues[i];
      const nextCue = lipsync.mouthCues[i + 1];
      
      // Scale times to match audio duration
      const scaledStart = mouthCue.start * timeScale;
      const scaledEnd = mouthCue.end * timeScale;
      
      if (currentAudioTime >= scaledStart && currentAudioTime <= scaledEnd) {
        const viseme = corresponding[mouthCue.value];
        if (viseme) {
          // Calculate intensity based on position in cue duration
          const cueProgress = (currentAudioTime - scaledStart) / (scaledEnd - scaledStart);
          
          // MAXIMUM MOUTH MOVEMENT - Very strong and active
          const intensity = 0.2 + (0.8 * Math.sin(cueProgress * Math.PI)); // 0.2 to 1.0 intensity
          
          appliedMorphTargets.push(viseme);
          lerpMorphTarget(viseme, intensity, 0.8); // Fast response for instant sync
          
          // Add secondary mouth movement for more activity
          if (mouthCue.value === 'A' || mouthCue.value === 'E' || mouthCue.value === 'I') {
            // For vowels, add strong jaw opening
            lerpMorphTarget('viseme_PP', intensity * 8, 0.5);
            // Add additional mouth opening for vowels
            lerpMorphTarget('viseme_AA', intensity * 0.6, 0.5);
            // Show more teeth during vowel sounds
            lerpMorphTarget('viseme_FF', intensity * 0.8, 0.5);
          } else if (mouthCue.value === 'B' || mouthCue.value === 'F') {
            // For consonants, add mouth closing
            lerpMorphTarget('viseme_kk', intensity * 0.4, 0.5);
            // Show maximum teeth for F sound
            if (mouthCue.value === 'F') {
              lerpMorphTarget('viseme_FF', intensity * 1.2, 0.5);
            }
          } else if (mouthCue.value === 'O' || mouthCue.value === 'U') {
            // For rounded vowels, add mouth rounding
            lerpMorphTarget('viseme_O', intensity * 0.7, 0.5);
            // Show teeth for rounded vowels
            lerpMorphTarget('viseme_FF', intensity * 0.6, 0.5);
          } else if (mouthCue.value === 'H' || mouthCue.value === 'X') {
            // For fricatives and default, show more teeth
            lerpMorphTarget('viseme_FF', intensity * 0.7, 0.5);
          }
          
          // Add constant mouth movement during speech
          lerpMorphTarget('viseme_TH', intensity * 0.3, 0.8);
          // Always show more teeth during speech
          lerpMorphTarget('viseme_FF', intensity * 0.5, 0.8);
        }
        break;
      }
      
      // Pre-transition to next cue for ultra-smooth animation
      if (nextCue && currentAudioTime > scaledEnd && currentAudioTime < nextCue.start * timeScale) {
        const transitionProgress = (currentAudioTime - scaledEnd) / (nextCue.start * timeScale - scaledEnd);
        const currentViseme = corresponding[mouthCue.value];
        const nextViseme = corresponding[nextCue.value];
        
        if (currentViseme && nextViseme) {
          // Ultra-smooth transition between visemes
          lerpMorphTarget(currentViseme, 1 - transitionProgress, 0.03);
          lerpMorphTarget(nextViseme, transitionProgress, 0.03);
          appliedMorphTargets.push(currentViseme, nextViseme);
          
          // Add micro-movements during transitions
          const microIntensity = 0.2 + (0.1 * Math.sin(transitionProgress * Math.PI * 2));
          lerpMorphTarget('viseme_PP', microIntensity, 0.05);
        }
        break;
      }
    }

    // Keep mouth slightly active even between cues for natural look
    if (appliedMorphTargets.length === 0 && currentAudioTime < audioDuration) {
      // Slight mouth movement when no specific cue is active
      const idleIntensity = 0.1 + (0.05 * Math.sin(currentAudioTime * 10));
      lerpMorphTarget('viseme_PP', idleIntensity, 0.1);
    }

    // Fade out unused visemes instantly for clean animation
    Object.values(corresponding).forEach((value) => {
      if (!appliedMorphTargets.includes(value)) {
        lerpMorphTarget(value, 0, 0.1); // Instant fade out
      }
    });
  });

  useControls("FacialExpressions", {
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: filteredAnimations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      if (!isModelLoaded) return;
      
      try {
        const emotionValues = {};
        Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
          if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
            return; // eyes wink/blink are handled separately
          }
          try {
            const index = nodes.EyeLeft.morphTargetDictionary[key];
            if (index !== undefined) {
              const value = nodes.EyeLeft.morphTargetInfluences[index];
              if (value !== undefined && value > 0.01) {
                emotionValues[key] = value;
              }
            }
          } catch (e) {
            // Skip invalid morph targets
            if (process.env.NODE_ENV === 'development') {
              console.warn(`Error reading morph target ${key}:`, e);
            }
          }
        });
        console.log(JSON.stringify(emotionValues, null, 2));
      } catch (e) {
        console.warn('Error logging morph target values:', e);
      }
    }),
  });

  const [, set] = useControls("MorphTarget", () => {
    // Return an empty object to avoid Leva errors
    // The morph target controls were causing too many issues with dynamic updates
    return {};
  });

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <>
      {isModelLoaded ? (
        <group {...props} dispose={null} ref={group}>
          <primitive object={nodes.Hips} />
          <skinnedMesh
            name="Wolf3D_Body"
            geometry={nodes.Wolf3D_Body.geometry}
            material={materials.Wolf3D_Body}
            skeleton={nodes.Wolf3D_Body.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Bottom"
            geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
            material={materials.Wolf3D_Outfit_Bottom}
            skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Footwear"
            geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
            material={materials.Wolf3D_Outfit_Footwear}
            skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Outfit_Top"
            geometry={nodes.Wolf3D_Outfit_Top.geometry}
            material={materials.Wolf3D_Outfit_Top}
            skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
          />
          <skinnedMesh
            name="Wolf3D_Hair"
            geometry={nodes.Wolf3D_Hair.geometry}
            material={materials.Wolf3D_Hair}
            skeleton={nodes.Wolf3D_Hair.skeleton}
          />
          <skinnedMesh
            name="EyeLeft"
            geometry={nodes.EyeLeft.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeLeft.skeleton}
            morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
          />
          <skinnedMesh
            name="EyeRight"
            geometry={nodes.EyeRight.geometry}
            material={materials.Wolf3D_Eye}
            skeleton={nodes.EyeRight.skeleton}
            morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
            morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Head"
            geometry={nodes.Wolf3D_Head.geometry}
            material={materials.Wolf3D_Skin}
            skeleton={nodes.Wolf3D_Head.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
          />
          <skinnedMesh
            name="Wolf3D_Teeth"
            geometry={nodes.Wolf3D_Teeth.geometry}
            material={materials.Wolf3D_Teeth}
            skeleton={nodes.Wolf3D_Teeth.skeleton}
            morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
            morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
          />
        </group>
      ) : (
        <group {...props} ref={group}>
          {/* Loading placeholder or fallback */}
          <mesh>
            <boxGeometry args={[1, 1, 1]} />
            <meshStandardMaterial color="gray" wireframe />
          </mesh>
        </group>
      )}
    </>
  );
}

useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useGLTF.preload("/models/animations.glb");